os:
  - linux
  - osx
language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - os: osx
script:
  - cargo build --features latest --verbose
  - cargo test --features latest --verbose
  - cargo build --features latest --release --verbose
  - cargo test --features latest --release --verbose
  - cargo bench --features latest
  - cargo doc --features latest
notifications:
  slack: rustyhorde:qUn6626kqV2JaMsGUFLlNvJa
