os:
  - linux
  - osx
language: rust
rust:
  - 1.0.0
  - 1.1.0
  - 1.2.0
matrix:
  allow_failures:
    - os: osx
script:
  - cargo build --features latest --verbose
  - cargo test --features latest --verbose
  - cargo build --features latest --release --verbose
  - cargo test --features latest --release --verbose
  - cargo doc --features latest
notifications:
  slack: rustyhorde:qUn6626kqV2JaMsGUFLlNvJa
