environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    ARCH: amd64
  - TARGET: i686-pc-windows-msvc
    ARCH: x86
install:
  - git submodule update --init --recursive --merge
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.2.0-${env:TARGET}.exe"
  - rust-1.2.0-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --verbose
